# NumPy
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

- NumPy is a python library, stands for Numerical Python
- Used for working with arrays. It is very useful in Numerical calculations - matrices, linear algebra, etc
- The array object in NumPy is called ndarray (n-dimensional array). Arrays are frequently used in data sciences, where speed and accuracy matters. It is similar to list but it is way faster than that.
- Elements in NumPy array cannot be heterogeneous like in lists. The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.
- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
- NumPy library was written partially in Python, but most of the parts that require fast computation are written in C or C++.
- For detailed information you can go through the [official documentation](https://numpy.org/doc/stable/user/absolute_beginners.html#numpy-the-absolute-basics-for-beginners) 
- [Source code for NumPy](https://github.com/numpy/numpy)

In [1]:
# To import the library use
import numpy

In [2]:
# add keyword numpy before using
a = numpy.array([1,2,3,4,5]) # defines a as numpy object 
# array is enclosed in ([])

NumPy is imported under the alias using the keyword "as" - import numpy as np  
This shortens the keyword required in syntax, instead of numpy.array we can type np.array

In [3]:
import numpy as np
a = np.array([1,2,3,4,5])
b = [1,2,3,4,5]
print(a)
print(b)
print(type(a)) # shows the type
print(type(b))

[1 2 3 4 5]
[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>
<class 'list'>


Notice the output of print(a), it is enclosed in square brackets like lists but not separated by commas like lists. Hence the output is a numpy array.

In [4]:
#Use Tuple to create numpy array
import numpy as np
a = np.array((1,2,3,4,5))
print(a)
print(type(a))
# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method.

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Dimensions in Array
A dimension in array is one level of array depth

- nested arrays: are arrays that have arrays as elements.

#### Check Number of Dimensions of array
*ndim* attribute returns an integer that tells us how many dimensions an array has

if a is defined as an array, to check the dimensions of a, the syntax is - a.ndim

### 0-D Arrays
- 0-D Arrays or scalars are elements in array, each value in array is 0-D array.

In [5]:
import numpy as np
a = np.array(9) # single element
print(a)
print(a.ndim) #prints the dimension of an array

9
0


### 1-D Arrays
An array that has 0D Arrays as its elements.

In [6]:
a = np.array([1,2,3,4,5])
print(a)
print(a.ndim)

[1 2 3 4 5]
1


### 2-D Arrays
An array that has 1-D elements is called a 2D array

Represents a matrix

Note: NumPy also has a submodule dedicated for matrix operations called numpy.mat (go through [documentation](https://numpy.org/doc/stable/reference/generated/numpy.mat.html))

In [7]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
2


### 3-D Arrays
An array of 2D arrays is called a 3D array.

In [8]:
import numpy as np
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]])
print(a)
print(a.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]]
3


In [9]:
# Common example to demonstrate dimensions
import numpy as np
a = np.array(45)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
e = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
# Pay very close attention to the number of square brackets.
# One neat trick is the number of square brackets at the beginning is the dimensions of that array.
print(a,'\n')
print(b,'\n')
print(c,'\n')
print(d,'\n')
print(e,'\n')

print("The dimension of",'\n',a,"is --",a.ndim)
print("The dimension of",'\n',b,"is --",b.ndim)
print("The dimension of",'\n',c,"is --",c.ndim)
print("The dimension of",'\n',d,"is --",d.ndim)
print("The dimension of",'\n',e,"is --",e.ndim)

45 

[1 2 3 4 5] 

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] 

The dimension of 
 45 is -- 0
The dimension of 
 [1 2 3 4 5] is -- 1
The dimension of 
 [[1 2 3]
 [4 5 6]] is -- 2
The dimension of 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] is -- 2
The dimension of 
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] is -- 3


In [10]:
# To make an array of desired dimensions
a = np.array([1,2,3,4],ndmin=7)
print(a)
print("Number of dimensions: ",a.ndim)

[[[[[[[1 2 3 4]]]]]]]
Number of dimensions:  7


## Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

In [11]:
import numpy as np
a = np.array([1,2,3,4])
print(a[0]) # Remember! first element has 0 index in python

1


In [12]:
'''To access elements from 2-D arrays we can use comma separated integers representing 
the dimension and the index of the element.'''

a = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
#[1,2,3,4,5] = 0th dimension, [6,7,8,9,10] = 1st dimension

print(a[0,1]) # first index = 0 ->selects 1st array, second index = 1 ->selects second element of first array

2


In [13]:
print(a[1,3]) #syntax - a[dimension,element]

9


In [14]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a[0,1,1]) 
'''
first index = 0 -> Selects [[1,2,3],[4,5,6]]
second index = 1 -> Selects [4,5,6]
third index = 1 -> Selects 5
'''
print("Dimensions of a: ",a.ndim)

5
Dimensions of a:  3


In [15]:
a.shape


(2, 2, 3)

a has 2 elements `[[1,2,3],[4,5,6]]` & `[[7,8,9],[10,11,12]]`  
of which each has 2 elements `[1,2,3]` & `[4,5,6]` of 1st element; `[7,8,9]` & `[10,11,12]` of 2nd element  
of which each has 3 elements `1,2,3` .... and so on you get the point  
`a.shape` returns (2,2,3) which is the shape of an array  

## Slicing Arrays
Syntax [start_inclusive:end_exclusive]

also

[start:end:step]

Leaving start or end index blank will mean start from beginning and go till end respectively

In [16]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[1:5]) # From 1st index to 4th index

[2 3 4 5]


In [17]:
a[:5] # From beginning to 4th index

array([1, 2, 3, 4, 5])

In [18]:
a[5:]

array([6, 7, 8, 9])

In [19]:
a[2:6:2] # from index 2 to 5 in steps of 2

array([3, 5])

In [20]:
b = np.array([1,2,3,4,5,6,7])
c = np.array_split(b,3) # array_split(array,no. of splits)
print(c)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


## Random
NumPy has a function `random` which creates an array of given shape and populate it with random samples from a uniform distribution over `[0,1)` [Documentation](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

In [21]:
# import random from numpy so that we don't have to write np.random.rand()
from numpy import random 
x = random.rand() #returns a random float between 0 and 1
x

0.872575143209844

`random.randint(low, high=None, size=None, dtype=int)`  
Return random integers from low (inclusive) to high (exclusive).  

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).  
[Documentation](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html#numpy-random-randint)

In [22]:
x = random.randint(100, size=(5)) #gives an array of 5 random integers between 0 and 100
x

array([35, 71, 96, 22, 87])

In [23]:
x = random.randint(100, size=(3,3)) # gives a 3 x 3 array
x

array([[32, 24, 91],
       [93, 93, 62],
       [ 6, 48, 78]])

In [24]:
x = random.choice([3,5,7,9]) # chooses a random value from given array
x

3

In [25]:
x = random.choice([3,5,7,9],size=(3,3)) # creates a 3 x 3 array by choosing values randomly from given array
x

array([[9, 5, 9],
       [7, 3, 9],
       [3, 9, 7]])

In [26]:
x = random.randint(100, size=(5))
y = np.random.shuffle(x)
print(x)
print(y)

[42 95 47 59 94]
None


In [27]:
x = random.randint(1000,size=(10)) # 10 random values between 0 and 1000
print(x) 
print(np.var(x)) # Variance
print(np.std(x)) # Standard Deviation
print(np.average(x)) # Average

[919 804  37  73 114 700 633 176 885 946]
131524.01
362.6623912125436
528.7


`np.random.randn()` returns a sample(or samples) from the "Standard Normal" Distribution.  
If positive int_like arguments are provided, `randn` generates an array of shape (d0,d1,...,dn), filled with random floats sampled from a univariate "normal" (Gaussian) distribution of mean 0 and variance 1. A single float randomly sampled from the distribution is returned if no argument is provided.

In [28]:
x = np.random.randn(10)
x

array([ 0.72307843, -0.59882514,  0.1692838 ,  0.60466727,  1.35625227,
        0.52099528, -0.78809752,  0.54377725, -0.92040102, -0.63293669])

Modify a sequence in-place by shuffling its contents.

This function only shuffles the array along the first axis of a multi-dimensional array. The order of sub-arrays is changed but their contents remains the same.

In [29]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
random.shuffle(x) 
x 

array([ 3, 10,  9,  5,  8,  1,  4,  2,  6,  7])

## Products

In [30]:
p1 = np.inner(2,2) # gives inner product

v_a = 9 + 6j
v_b = 5 + 2j
p2 = np.inner(v_a,v_b) # inner product of 2 vectors
print(p1) 
print(p2)

4
(33+48j)


In [31]:
a1 = np.array([[2,6],[7,8]])
a2 = np.array([[5,10],[-2,3]])
p3 = np.inner(a1,a2)
print(p3)

[[ 70  14]
 [115  10]]


In [34]:
a1*a2

array([[ 10,  60],
       [-14,  24]])

In [32]:
# Cross Product
p4 = np.cross(a1,a2)
print(p4)

[-10  37]


In [33]:
# Dot Product
p5 = np.dot(a1,a2)
p5

array([[-2, 38],
       [19, 94]])

If we just want the indices where a certain condition is satisfied, we can use `np.where( )`. This function is used to filter out data.

In [34]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
indices = np.where(x<5)
x[indices]

array([0, 1, 2, 3, 4])

**Functions like np.arange, np.linspace are very useful:**

np.arange (read as 'a range') gives an array of numbers within a given range and stepsize

np.linspace gives an array of linearly spaced numbers

In [35]:
np.arange(0,10,3) # syntax - (inclusive_start, exclusive_stop, stepsize)
#This will give an array of values from 0 to 10 in steps of 3

array([0, 3, 6, 9])

In [36]:
np.arange(-np.pi, np.pi, 1) 

array([-3.14159265, -2.14159265, -1.14159265, -0.14159265,  0.85840735,
        1.85840735,  2.85840735])

In [37]:
np.linspace(-np.pi, np.pi, 7) # linearly spaced values - difference between 2 consecutive values not necessarily 1

array([-3.14159265, -2.0943951 , -1.04719755,  0.        ,  1.04719755,
        2.0943951 ,  3.14159265])

**Notice** the difference between `np.arange()` function and `np.linspace()` function:

`np.arange` function gives values which have same difference but doesn't include the last value, whereas `np.linspace` function first sets start and end value and divides the numbers linearly.

This changes the output of both of these function significantly. 

In the syntax of `np.arange` function the **last value denotes the difference between each element**. But in `np.linspace` function the **last value denotes the number of elements desired in the given range**, the difference between each element is determined accoridingly by the system.

In [38]:
np.linspace(0,np.pi,10) #syntax - (inclusive_start, INCLUSIVE_stop, Number of elements)

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

## NumPy Logarithms
NumPy has functions to perform log at base 2, e and 10
- `log2()` - log to the base 2
- `log10()` - log to the base 10
- `log()` - natural log / base $\mathcal{e}$

In [39]:
#log to the base 2
x = np.arange(1,10)
print(x)
print(np.log2(x))

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [40]:
# log to the base 10
print(np.log10(x))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [41]:
# log to the base e or natural log (ln)
print(np.log(x))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


## NumPy LCM and GCD
NumPy has the functions `np.lcm` and `np.gcd`. 

We can also use this functions to find lcm and gcd of each element in an array using the $reduce( )$ method

In [42]:
x = 4
y = 12
lcm = np.lcm(x,y)
lcm

12

In [43]:
gcd = np.gcd(x,y)
gcd

4

In [44]:
x = np.arange(2,10)
y = np.lcm.reduce(x) # use reduce() when the element is an array
y

2520

In [45]:
x = np.array([4,44,40,20,22])
np.gcd.reduce(x)

2

In [46]:
x = np.random.randint(100,size=2)
print(x)
print(np.gcd.reduce(x))

[81 33]
3


## Convert Degrees into Radians and Radians to Degrees
By default the values are in radians, but we can convert it into degrees and vice versa if required

$$180^\circ=\pi\;rad$$
$$\therefore 1\;rad=\Big(\frac{180}{\pi}\Big)^\circ$$

In [47]:
# Suppose we have array of values in degrees
import numpy as np
x = np.array([0,30,45,60,90,180,270,360])
radian = np.deg2rad(x)
print(radian)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 3.14159265
 4.71238898 6.28318531]


In [48]:
degree = np.rad2deg(radian)
print(degree)

[  0.  30.  45.  60.  90. 180. 270. 360.]


In [49]:
y = np.array([np.pi/2, np.pi, 4*np.pi/3, 2*np.pi])
y_degree = np.rad2deg(y)
print(y_degree)

[ 90. 180. 240. 360.]


NumPy also has the function to find angles i.e inverse trig values

arcsin( ), arccos( ), arctan( )

In [50]:
x = np.arcsin(0.8)
x_deg = np.rad2deg(x)
print(x)
print(round(x_deg,2)) # round(x_deg,2) rounds off the value of x_deg to 2 decimal places

0.9272952180016123
53.13
